name: Create Release

on:
  push:
    tags:
      - '*.*.0'

permissions:
  contents: write

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up user
        shell: bash
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get previous tag
        id: prev_tag
        run: |
          PREV_TAG=$(git tag --sort=-creatordate | grep -v "${GITHUB_REF_NAME}" | head -n 1)
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_ENV

      - name: Set release notes with commits since last tag
        id: set-notes
        run: |
          VERSION="${GITHUB_REF_NAME}"
          PREV="${PREV_TAG}"
          if [ -z "$PREV" ]; then
          BODY=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
          BODY=$(git log "$PREV"..HEAD --pretty=format:"- %s (%h)" --no-merges)
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE_NOTES=Release $VERSION\n\nCommits since $PREV:\n$BODY" >> $GITHUB_ENV

      - name: Push release
        id: push-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: "Release ${{ env.VERSION }}"
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
